version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi_app
    ports:
      - "1337:1337"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production

  db:
    image: postgres:15
    container_name: strapi_db
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: