version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi_app
    ports:
      - "1337:1337"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - ./app:/srv/app
      - ./data:/srv/app/.tmp   # supaya data sqlite tidak hilang